//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Özgür/Scripts/PlayerScripts/NoTouch/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a91b47db-e1f5-4edc-84a2-a63850aebbfa"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""8347f867-5017-4a3f-9534-e7f7d1838122"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""fdbea76b-3538-4849-88a2-88d8c3a3f5f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""e97e4576-bf6b-4347-a305-5d21115f8601"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryAbility"",
                    ""type"": ""Button"",
                    ""id"": ""d3e0a102-59cb-4f4b-b212-16584e035e65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAbility"",
                    ""type"": ""Button"",
                    ""id"": ""76d1b2bc-4a53-4553-aa9a-53d037b6daaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MapKey"",
                    ""type"": ""Button"",
                    ""id"": ""5d2ca2aa-0e16-4d14-8ece-75769cde3270"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EasterEgg"",
                    ""type"": ""Button"",
                    ""id"": ""21cf2b50-e2e5-4d7c-8d24-bfa50f211aea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QTEUp"",
                    ""type"": ""Button"",
                    ""id"": ""aaed9830-448b-41cb-bac4-7e2e9e65c1e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QTEDown"",
                    ""type"": ""Button"",
                    ""id"": ""9d5d52ea-0dea-43d1-9264-18178c246144"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QTERight"",
                    ""type"": ""Button"",
                    ""id"": ""a9fb66e3-712c-44a2-b460-fe7171bac55a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QTELeft"",
                    ""type"": ""Button"",
                    ""id"": ""d087d693-c35f-4951-ba99-54dfce30598b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""7c336175-d76e-4ff6-a397-0a422b28d0cf"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""37de2130-4376-47a1-ac1c-43cf8705dafa"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e93ec95e-351f-43a3-aa20-6272261e714a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d989184b-ed9c-4a58-b946-34f3e834a5aa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7e9792d4-6074-4e97-9eaa-72426a075cca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""aa656a7c-1421-4cba-b959-bfb2ee9ac98a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e7a5c025-9c60-47af-81ec-f9ee2012ba5b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""42d589dd-b245-4846-8f42-927f11bd2cf8"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ac79bb96-fb7c-4774-8692-14e14804feb9"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b8c9dfab-c0b8-471a-9579-4e73cec52008"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a5519d95-dbdc-48ff-8c71-7079a76d5c37"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d0a4239-326a-41f6-a7ac-515ec539e5eb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccff50e3-9be4-444d-b262-54319cd49068"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""625e86ca-d412-4b13-bdaf-696d42f971fd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d9e6b98-d339-49d1-9748-1b0a2ef91d83"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1776eb46-1e0b-4433-9a03-edc8498ce9a1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e48a197-dab7-46a5-bb93-ab7b1246787e"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc6b879f-40e2-4b41-be4c-079af289271a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""233b5c54-6f12-46d5-9f61-ff95394be1e5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43bc7133-7eae-4c5e-8bcd-12353f7b9c5f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1670f202-ebf5-4710-83df-2c4a1e9a51d0"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EasterEgg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79b59003-2623-4a18-932c-61e3f8663870"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QTEUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a524167e-5b3c-4348-a83c-7a22c28a1651"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QTEDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96b1d5ac-c20a-4104-a164-8dea5651246e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QTERight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59feb968-5b77-48e0-beb8-db54b7388949"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QTELeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Grab = m_Player.FindAction("Grab", throwIfNotFound: true);
        m_Player_PrimaryAbility = m_Player.FindAction("PrimaryAbility", throwIfNotFound: true);
        m_Player_SecondaryAbility = m_Player.FindAction("SecondaryAbility", throwIfNotFound: true);
        m_Player_MapKey = m_Player.FindAction("MapKey", throwIfNotFound: true);
        m_Player_EasterEgg = m_Player.FindAction("EasterEgg", throwIfNotFound: true);
        m_Player_QTEUp = m_Player.FindAction("QTEUp", throwIfNotFound: true);
        m_Player_QTEDown = m_Player.FindAction("QTEDown", throwIfNotFound: true);
        m_Player_QTERight = m_Player.FindAction("QTERight", throwIfNotFound: true);
        m_Player_QTELeft = m_Player.FindAction("QTELeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Grab;
    private readonly InputAction m_Player_PrimaryAbility;
    private readonly InputAction m_Player_SecondaryAbility;
    private readonly InputAction m_Player_MapKey;
    private readonly InputAction m_Player_EasterEgg;
    private readonly InputAction m_Player_QTEUp;
    private readonly InputAction m_Player_QTEDown;
    private readonly InputAction m_Player_QTERight;
    private readonly InputAction m_Player_QTELeft;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Grab => m_Wrapper.m_Player_Grab;
        public InputAction @PrimaryAbility => m_Wrapper.m_Player_PrimaryAbility;
        public InputAction @SecondaryAbility => m_Wrapper.m_Player_SecondaryAbility;
        public InputAction @MapKey => m_Wrapper.m_Player_MapKey;
        public InputAction @EasterEgg => m_Wrapper.m_Player_EasterEgg;
        public InputAction @QTEUp => m_Wrapper.m_Player_QTEUp;
        public InputAction @QTEDown => m_Wrapper.m_Player_QTEDown;
        public InputAction @QTERight => m_Wrapper.m_Player_QTERight;
        public InputAction @QTELeft => m_Wrapper.m_Player_QTELeft;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Grab.started += instance.OnGrab;
            @Grab.performed += instance.OnGrab;
            @Grab.canceled += instance.OnGrab;
            @PrimaryAbility.started += instance.OnPrimaryAbility;
            @PrimaryAbility.performed += instance.OnPrimaryAbility;
            @PrimaryAbility.canceled += instance.OnPrimaryAbility;
            @SecondaryAbility.started += instance.OnSecondaryAbility;
            @SecondaryAbility.performed += instance.OnSecondaryAbility;
            @SecondaryAbility.canceled += instance.OnSecondaryAbility;
            @MapKey.started += instance.OnMapKey;
            @MapKey.performed += instance.OnMapKey;
            @MapKey.canceled += instance.OnMapKey;
            @EasterEgg.started += instance.OnEasterEgg;
            @EasterEgg.performed += instance.OnEasterEgg;
            @EasterEgg.canceled += instance.OnEasterEgg;
            @QTEUp.started += instance.OnQTEUp;
            @QTEUp.performed += instance.OnQTEUp;
            @QTEUp.canceled += instance.OnQTEUp;
            @QTEDown.started += instance.OnQTEDown;
            @QTEDown.performed += instance.OnQTEDown;
            @QTEDown.canceled += instance.OnQTEDown;
            @QTERight.started += instance.OnQTERight;
            @QTERight.performed += instance.OnQTERight;
            @QTERight.canceled += instance.OnQTERight;
            @QTELeft.started += instance.OnQTELeft;
            @QTELeft.performed += instance.OnQTELeft;
            @QTELeft.canceled += instance.OnQTELeft;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Grab.started -= instance.OnGrab;
            @Grab.performed -= instance.OnGrab;
            @Grab.canceled -= instance.OnGrab;
            @PrimaryAbility.started -= instance.OnPrimaryAbility;
            @PrimaryAbility.performed -= instance.OnPrimaryAbility;
            @PrimaryAbility.canceled -= instance.OnPrimaryAbility;
            @SecondaryAbility.started -= instance.OnSecondaryAbility;
            @SecondaryAbility.performed -= instance.OnSecondaryAbility;
            @SecondaryAbility.canceled -= instance.OnSecondaryAbility;
            @MapKey.started -= instance.OnMapKey;
            @MapKey.performed -= instance.OnMapKey;
            @MapKey.canceled -= instance.OnMapKey;
            @EasterEgg.started -= instance.OnEasterEgg;
            @EasterEgg.performed -= instance.OnEasterEgg;
            @EasterEgg.canceled -= instance.OnEasterEgg;
            @QTEUp.started -= instance.OnQTEUp;
            @QTEUp.performed -= instance.OnQTEUp;
            @QTEUp.canceled -= instance.OnQTEUp;
            @QTEDown.started -= instance.OnQTEDown;
            @QTEDown.performed -= instance.OnQTEDown;
            @QTEDown.canceled -= instance.OnQTEDown;
            @QTERight.started -= instance.OnQTERight;
            @QTERight.performed -= instance.OnQTERight;
            @QTERight.canceled -= instance.OnQTERight;
            @QTELeft.started -= instance.OnQTELeft;
            @QTELeft.performed -= instance.OnQTELeft;
            @QTELeft.canceled -= instance.OnQTELeft;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
        void OnPrimaryAbility(InputAction.CallbackContext context);
        void OnSecondaryAbility(InputAction.CallbackContext context);
        void OnMapKey(InputAction.CallbackContext context);
        void OnEasterEgg(InputAction.CallbackContext context);
        void OnQTEUp(InputAction.CallbackContext context);
        void OnQTEDown(InputAction.CallbackContext context);
        void OnQTERight(InputAction.CallbackContext context);
        void OnQTELeft(InputAction.CallbackContext context);
    }
}
